// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	sharedtypes "github.com/T-V-N/gopherstore/internal/shared_types"
	mock "github.com/stretchr/testify/mock"
)

// OrderApper is an autogenerated mock type for the OrderApper type
type OrderApper struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, orderID, uid
func (_m *OrderApper) CreateOrder(ctx context.Context, orderID string, uid string) error {
	ret := _m.Called(ctx, orderID, uid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orderID, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUnproccessedOrders provides a mock function with given fields: ctx
func (_m *OrderApper) GetUnproccessedOrders(ctx context.Context) ([]sharedtypes.Order, error) {
	ret := _m.Called(ctx)

	var r0 []sharedtypes.Order
	if rf, ok := ret.Get(0).(func(context.Context) []sharedtypes.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sharedtypes.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrders provides a mock function with given fields: ctx, uid
func (_m *OrderApper) ListOrders(ctx context.Context, uid string) ([]sharedtypes.Order, error) {
	ret := _m.Called(ctx, uid)

	var r0 []sharedtypes.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) []sharedtypes.Order); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sharedtypes.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrder provides a mock function with given fields: ctx, uid, orderID, amount, user
func (_m *OrderApper) UpdateOrder(ctx context.Context, uid string, orderID string, amount float32, user sharedtypes.UserApper) error {
	ret := _m.Called(ctx, uid, orderID, amount, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float32, sharedtypes.UserApper) error); ok {
		r0 = rf(ctx, uid, orderID, amount, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOrderApper interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderApper creates a new instance of OrderApper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderApper(t mockConstructorTestingTNewOrderApper) *OrderApper {
	mock := &OrderApper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
