// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	sharedtypes "github.com/T-V-N/gopherstore/internal/shared_types"
	mock "github.com/stretchr/testify/mock"
)

// OrderStorage is an autogenerated mock type for the OrderStorage type
type OrderStorage struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: _a0, _a1, _a2
func (_m *OrderStorage) CreateOrder(_a0 context.Context, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUnproccessedOrders provides a mock function with given fields: _a0
func (_m *OrderStorage) GetUnproccessedOrders(_a0 context.Context) ([]sharedtypes.Order, error) {
	ret := _m.Called(_a0)

	var r0 []sharedtypes.Order
	if rf, ok := ret.Get(0).(func(context.Context) []sharedtypes.Order); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sharedtypes.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrders provides a mock function with given fields: _a0, _a1
func (_m *OrderStorage) ListOrders(_a0 context.Context, _a1 string) ([]sharedtypes.Order, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []sharedtypes.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) []sharedtypes.Order); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sharedtypes.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrder provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *OrderStorage) UpdateOrder(_a0 context.Context, _a1 string, _a2 string, _a3 float32, _a4 sharedtypes.UserStorage) error {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float32, sharedtypes.UserStorage) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOrderStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderStorage creates a new instance of OrderStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderStorage(t mockConstructorTestingTNewOrderStorage) *OrderStorage {
	mock := &OrderStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
